#-------------------------------------------------------------------------------
# Workflow configuration
#-------------------------------------------------------------------------------

name: "Mobile CI builds"
on: workflow_dispatch

#-------------------------------------------------------------------------------
# Define application name & version
#-------------------------------------------------------------------------------

env:
  VERSION: "1.0"
  APPLICATION: "Theengs"
  QMAKE_PROJECT: "Theengs.pro"

#-------------------------------------------------------------------------------
# Workflow jobs
#-------------------------------------------------------------------------------

jobs:
  ## Android build #############################################################
  build-android:
    name: "Android CI build"
    runs-on: ubuntu-20.04
    steps:
      # Checkout the repository
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Java environment (already installed in 'ubuntu-20.04')
      #- name: Install JDK environment
      #  uses: actions/setup-java@v2
      #  with:
      #    distribution: 'zulu'
      #    java-version: '11'

      # Android environment (already installed in 'ubuntu-20.04')
      #- name: Setup Android SDK
      #  uses: android-actions/setup-android@v2
      #- name: Install Android SDK / NDK / tools
      #  run: |
      #       sdkmanager "platforms;android-32"
      #       sdkmanager "ndk;23.1.7779620"
      #       sdkmanager "build-tools;30.0.3"

      # Install Qt (desktop)
      - name: Install Qt (desktop)
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==2.1.0'
          version: '6.3.1'
          modules: qtconnectivity qtwebsockets qtcharts qtimageformats qt5compat
          cached: 'false'

      # Install Qt (Android)
      - name: Install Qt (Android)
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==2.1.0'
          version: '6.3.1'
          host: 'linux'
          target: 'android'
          arch: 'android_arm64_v8a'
          modules: qtconnectivity qtwebsockets qtcharts qtimageformats qt5compat
          cached: 'false'

      # Install Ninja
      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@master

      # Setup env
      - name: Setup env
        run: |
             sudo apt-get install cmake ninja-build libtool automake m4 gettext -y
             export PATH=$Qt6_DIR/bin:$PATH
             qmake --version
             ninja --version

      # Build dependencies (from contribs script)
      - name: Build dependencies (from contribs script)
        run: |
             cd contribs
             python3 contribs.py --mobile --qt-directory ${{env.Qt6_DIR}}/../../
             cd ..

      # Build application
      - name: Build application
        run: |
             qmake ${{env.QMAKE_PROJECT}} CONFIG+=release DEFINES+=QT_CONNECTIVITY_PATCHED
             make -j$(nproc)

  ## iOS build #################################################################
  build-ios:
    name: "iOS CI build"
    runs-on: macos-11
    steps:
      # Checkout the repository
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install Qt (desktop)
      - name: Install Qt (desktop)
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==2.1.0'
          version: '6.3.1'
          modules: qtconnectivity qtwebsockets qtcharts qtimageformats qt5compat
          cached: 'false'

      # Install Qt (iOS)
      - name: Install Qt (iOS)
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==2.1.0'
          version: '6.3.1'
          host: 'mac'
          target: 'ios'
          modules: qtconnectivity qtwebsockets qtcharts qtimageformats qt5compat
          cached: 'false'

      # Install Ninja
      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@master

      # Setup env
      - name: Setup env
        run: |
             brew install cmake ninja automake autoconf libtool pkg-config
             ln -s /Users/runner/work/${{env.APPLICATION}}/Qt/6.3.1/macos /Users/runner/work/${{env.APPLICATION}}/Qt/6.3.1/clang_64
             export PATH=$Qt6_DIR/bin:$PATH
             qmake --version

      # Build dependencies (from contribs script)
      - name: Build dependencies (from contribs script)
        run: |
             cd contribs
             python3 contribs.py --mobile --qt-directory ${{env.Qt6_DIR}}/../../
             cd ..

      # Build application
      - name: Build application
        run: |
             qmake ${{env.QMAKE_PROJECT}} CONFIG+=release
             make -j$(nproc)
